[package]
name = "shgl"
version = "0.1.0"
edition = "2024"

[dependencies]
gl = "0.14.0"
glm = "0.3.0"
gl_loader = "0.1.2"
image = "0.25.8"

[dependencies.glfw]
version = "0.60.0"
features = ["src-build"]
